# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cbf5e4cb0fb03e597ca86f62dd31518382af8784936d6100010829a33ff0b4031e93e93e7e900ac048406882a30f34593af4533e61df0c74c40d09e39717c8df

test:
  secret_key_base: 9a5dd7c2ee9e194b20ced14570e30b6e08dd253f35a9ccc7847a0fa39db14a083b872b54669af9d185712c09d8e268c23807fd83b24aca239448d274f4b47fca

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
